### ISSUE TITLE
Regarding browser compatability

### ISSUE THREAD

**Issue by manzt** [denoland/wasmbuild#105]
Thanks for all your work on such an interesting project. I notice that the tagline for `wasmbuild` is:

> "Build tool to use Rust code in Deno and the browser."

But when I've tried the tool, the generated code seems Deno-specific (TS, and Deno namespaces used). Is there a browser plan in the future for this build tool?

**Comment by dsherret** [comment]
This is fixed in 0.15.5. I opened https://github.com/denoland/wasmbuild/issues/115 for adding a test for this to help prevent a regression in the future.
