### ISSUE TITLE
import `Loader` and `cacheToLocalDir` using relative path

### ISSUE THREAD

**Issue by iuioiua** [denoland/wasmbuild#109]
See https://github.com/denoland/wasmbuild/pull/108#discussion_r1406874569

**Comment by dsherret** [comment]
It should only be relative if the resolved specifier is `file:///`. If it's `https://` then it should stay as-is.

**Comment by iuioiua** [comment]
In what instances would the resolved specifier be prefixed with `https://`? Genuine question.

**Comment by dsherret** [comment]
When someone uses wasmbuild on another repo. It will then import those files from deno.land/x

Tn this case, wasmbuild is using wasmbuild on itself, so it needs to be relative only here.
