### ISSUE TITLE
--remap-path-prefix arguments might be encoded incorrectly in RUSTFLAGS

### ISSUE THREAD

**Issue by jeremyBanks** [denoland/wasmbuild#135]
:wave: Hello. I built the latest released version of \@std/crypto's wasm binary on my machine a few weeks ago. While looking at the data recently, I noticed that my local file paths were included in the wasm binary, which isn't supposed to be the case because we use `--remap-path-prefix` in `RUSTFLAGS` to replace local paths prefixes with something generic.

Comparing the current code setting RUSTFLAGS...
https://github.com/denoland/wasmbuild/blob/f89f6f3338bd74a52db7ac20596e6a79d5fb35e6/lib/pre_build.ts#L80-L81

...to an old version, back when the logic lived in a script in deno_std instead of this standalone tool...
https://github.com/denoland/deno_std/blob/7348d133a8011481e4ed76c6f84f3a4c7a51a844/_wasm_crypto/_build.ts#L44

...the only apparent difference is that the `'${root}'` and `'${home}'` are wrapped in single-quotes. I'm not sure how those are handled, but when I removed the single quotes in a local version of wasmbuild and rebuilt the \@std/crypto wasm binary, the paths were again remapped as I expected.

before:

```
$ strings target/wasm32-unknown-unknown/release/deno_std_wasm_crypto.wasm | grep cargo

ArrayVec: capacity exceeded in extend/from_iter/home/jeremy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blake3-1.5.1/src/lib.rs
[/home/jeremy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrayvec-0.7.4/src/arrayvec.rs
/home/jeremy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/keccak-0.1.5/src/lib.rsA round_count greater than KECCAK_F_ROUND_COUNT is not supported!
/home/jeremy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/block-buffer-0.10.4/src/lib.rs:
```

after:

```
$ strings target/wasm32-unknown-unknown/release/deno_std_wasm_crypto.wasm | grep cargo

ArrayVec: capacity exceeded in extend/from_iter~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blake3-1.5.1/src/lib.rs
[~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrayvec-0.7.4/src/arrayvec.rs
~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/keccak-0.1.5/src/lib.rsA round_count greater than KECCAK_F_ROUND_COUNT is not supported!
~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/block-buffer-0.10.4/src/lib.rs
```

I'm not sure why the quotes were added, so maybe this affects some other case, but if not perhaps it's worth removing them.

If they are required to handle paths which themselves contain `=` characters or something like that, I saw [a post on URLO](https://users.rust-lang.org/t/how-to-properly-use-remap-path-prefix/104406/6) suggesting a possible alternative, although I haven't tried this and am not sure exactly how it would be formatted:

> You can use `CARGO_ENCODED_RUSTFLAGS` instead which uses ASCII Unit Separator (`0x1f`) instead of space as argument separator. You can also use the new `--config` option to set the `build.rustflags` config to an array formatted as toml.

Thanks for reading.

**Comment by dsherret** [comment]
Probably related to https://github.com/denoland/wasmbuild/issues/98
