### ISSUE TITLE
Can we make `rustup` optional as a dependency?

### ISSUE THREAD

**Issue by hasundue** [denoland/wasmbuild#140]
I manage my environment with Nix, where Rust toolchains are managed by Nix itself instead of `rustup`. It is the more common and convenient way in the Nix ecosystem, as suggested by how popular the [rust-ovelay](https://github.com/oxalica/rust-overlay) repository is. I suppose there are other situations where Rust toolchains are managed by an alternative tool to `rustup`, not limited to the case of Nix.

In that situation, I found it very tricky to workaround `wasmbuild` requiring both `cargo` and `rustup`. Considering `rustup` is just used to add `wasm32-unknown-unknown` target, can we make `rustup` optional as a dependency and let users ensure the target installed by themselves if `rustup` does not exist?

I created a PR with my implementation to solve this, for additional information.

**Comment by dsherret** [comment]
Closed by https://github.com/denoland/wasmbuild/pull/141

Thanks!
