### ISSUE TITLE
Missing `cachedInt32Memory0`/`cachedUint8Memory0` Definitions

### ISSUE THREAD

**Issue by harrysolovay** [denoland/wasmbuild#21]
In [paritytech/capi](https://github.com/paritytech/capi), we utilize `wasmbuild` to create three separate wasm+binding pairs. [Here](https://github.com/paritytech/capi/blob/d108e2dda4e0e525b54a96f432f00b00f216d24d/deno.jsonc#L32) is the scripts that triggers this generation. For two of the three builds, this works just fine. The third build's JS bindings (sr25519 utils)––however––lack initialization of `cachedInt32Memory0`/`cachedUint8Memory0`, which results in a runtime error. We currently get around this by manually appending the variable declarations to the JS bindings file (as seen [here](https://github.com/paritytech/capi/blob/d108e2dda4e0e525b54a96f432f00b00f216d24d/_tasks/build_wasm.ts)). This is of course not ideal.

I suppose this also raises questions regarding creating multiple builds. Will open another issue.

**Comment by dsherret** [comment]
I ran into this the other day and this is fixed now.
