### ISSUE TITLE
Multiple Builds

### ISSUE THREAD

**Issue by harrysolovay** [denoland/wasmbuild#22]
I have a single crate, from which I'd like to generate three separate wasm builds. I have the crate root structured like so:

```rs
use wee_alloc::WeeAlloc;

#[global_allocator]
static ALLOC: WeeAlloc = WeeAlloc::INIT;

#[cfg(feature = "hashers")]
pub mod hashers;

#[cfg(feature = "sr25519")]
pub mod sr25519;

#[cfg(feature = "ss58")]
pub mod ss58;
```

Within my `deno.jsonc` tasks, I have the following.

```json
{
  ...
  "build_wasm": "deno run --unstable -A https://deno.land/x/wasmbuild@0.4.0/main.ts --out",
  "build_hashers_wasm": "deno task build_wasm bindings/hashers --features hashers",
  "build_sr25519_wasm": "deno task build_wasm bindings/sr25519 --features sr25519",
  "build_ss58_wasm": "deno task build_wasm bindings/ss58 --features ss58",
  "build_all_wasm": "deno task build_hashers_wasm && deno task build_sr25519_wasm && deno task build_ss58_wasm"
  ...
}
```

I have two questions:

1. Is there a simpler approach to building each feature into a separate wasm+binding pair? Something like a `--features-as-separate-builds` flag. I'd very much like to do away with 4 lines of task boilerplate.
2. Are there any optimizations that would enable the multiple builds to share some of the env glue? Each of these will bundle in the allocator... this isn't ideal. Any tips would be greatly appreciated.

**Comment by dsherret** [comment]
> Is there a simpler approach to building each feature into a separate wasm+binding pair? Something like a --features-as-separate-builds flag. I'd very much like to do away with 4 lines of task boilerplate.

I think it adds a bit too much complexity to this if we start having it do multiple builds per run instead of a single build per run. The setup you have doesn't seem too bad and it could be parallelized.

> Are there any optimizations that would enable the multiple builds to share some of the env glue? Each of these will bundle in the allocator... this isn't ideal. Any tips would be greatly appreciated.

That's a good idea. I opened #23.

**Comment by dsherret** [comment]
That would require wasmbuild needing to distribute a rust crate I think? All of this seems much more complicated than what's done in deno_std which seems very straightward. What's done in deno_std could also be parallelized across processes.

**Comment by harrysolovay** [comment]
Makes complete sense 👍
