### ISSUE TITLE
Recommended Compression/Decompression Approach

### ISSUE THREAD

**Issue by harrysolovay** [denoland/wasmbuild#47]
**Background**

PR #33 introduced the ability to specify a transform fn to the generated instantiation fn. AWESOME. The [`lz4`](https://deno.land/x/lz4@v0.1.2/mod.ts) lib is used in the example, which showcases decompression of some wasm before instantiation.

I have some **questions about this example usage and the feature more generally**:

- `lz4` uses top-level await, which means one cannot use it if they plan to target CJS –– is there a better / recommended alternative?
- it appears that this conflicts with `instantiateStreaming`? 
 
I suppose this series of questions is a bit scattered (apologies). A few more questions:

- what is the "best" way to use this feature?
- in what cases should one use (or not use) this feature?
- Any future plans to extend/tweak this feature?

Politely pinging @littledivy

**Comment by dsherret** [comment]
> lz4 uses top-level await, which means one cannot use it if they plan to target CJS –– is there a better / recommended alternative?

lz4 could expose an API that doesn't use a TLA.

> it appears that this conflicts with `instantiateStreaming`?
 
 Whatever issue there was here, it's probably fixed now

> Any future plans to extend/tweak this feature?

Not at the moment.
