### ISSUE TITLE
Uninitialized 'cachedUint32Memory0' is uninitialized

### ISSUE THREAD

**Issue by Oliver-makes-code** [denoland/wasmbuild#61]
In the generated JS files, the `cachedUint32Memory0` remains uninitialized, and when checking the byteLength, throws a `can't read properties of undefined` TypeError.

Generated code:
```js
let cachedUint32Memory0;
function getUint32Memory0() {
  if (cachedUint32Memory0.byteLength === 0) { // Need to check if cachedUint32Memory0 is undefined.
    cachedUint32Memory0 = new Uint32Array(wasm.memory.buffer);
  }
  return cachedUint32Memory0;
}
```

**Comment by Oliver-makes-code** [comment]
It looks like this issue is fixed in the latest commits, there just hasn't been a release yet.

**Comment by littledivy** [comment]
Released https://github.com/denoland/wasmbuild/releases/tag/0.10.3
