### ISSUE TITLE
Build in wasm-opt?

### ISSUE THREAD

**Issue by dsherret** [denoland/wasmbuild#7]
```
wasmbuild
wasm-opt -Oz lib/eszip_wasm_bg.wasm -o lib/eszip_wasm_bg.wasm
```

Would be nice to not require installing wasm-opt globally and just do:

```
wasmbuild --opt
```

Or perhaps do this by default and opt out with `--skip-opt`

**Comment by dsherret** [comment]
I think for this we're going to have to download the binary and save it in a temporary directory.

**Comment by harrysolovay** [comment]
This would be fantastic!
