### ISSUE TITLE
Support latest Wasm-Bindgen

### ISSUE THREAD

**Issue by seanaye** [denoland/wasmbuild#71]
This package fails to compile wasm-bindgen v0.2.84

**Comment by dsherret** [comment]
You can change your lockfile to `=0.2.83` or if that’s not sufficient then please submit a PR that bumps the versions in this repo.

**Comment by seanaye** [comment]
I drafted this https://github.com/denoland/wasmbuild/pull/72 but I receive `Runtime Unreachable` when I run it locally in my rust project

If I revert the deps in the rust project to v0.2.83 then it compiles properly so I think there might be an issue upstream? Or I am missing something in the PR

**Comment by dsherret** [comment]
Sorry, I should have linked here https://github.com/denoland/wasmbuild/blob/main/.github/contributing.md

**Comment by saoodahmad** [comment]
@dsherret can i work on the issue?

**Comment by dsherret** [comment]
@saoodahmad thanks, but it's already being worked on

**Comment by dsherret** [comment]
In 0.10.4
