### ISSUE TITLE
Consider updating rust toolchain version

### ISSUE THREAD

**Issue by sigmaSd** [denoland/wasmbuild#82]
I use the new cargo sparse protocol https://blog.rust-lang.org/inside-rust/2023/01/30/cargo-sparse-protocol.html, I have to set $CARGO_REGISTRIES_CRATES_IO_PROTOCOL to null to be able to build this project currently

Its a very nice improvement for cargo, so  if there is no issue in updating rust version, it would be great if this get bumped to 1.68.0

**Comment by dsherret** [comment]
Yes, please. We always try to use the latest Rust.

**Comment by sigmaSd** [comment]
but you still want a fixed version right ? so I can't just do `channel = "stable"` ?

**Comment by dsherret** [comment]
Yeah, fixed version.
