### ISSUE TITLE
Should lib/wasmbuild.generated.js lib/wasmbuild_bg.wasm not be version controlled

### ISSUE THREAD

**Issue by sigmaSd** [denoland/wasmbuild#86]
currently they are out of sync as in if you run deno task build, they will change

The problem is wasmbuild_bg.wasm for example will change depending on --skip-opt is present or not
I imagine other cli flags can affect these files as well

Solution:
- Manually update this for the default `deno task wasmbuild` run with no arguments
- Add them to gitignore but maybe that wont work becasue they are needed for this repo to work as a module remotly

**Comment by dsherret** [comment]
It depends. If the Rust code is not updated often then it might make sense to just check it in (I do that with dnt and Dax). Then the output is verified with `deno task wasmbuild --check`.

For the case of something else where the Rust code changes a lot and it's mainly a Rust project, then it might make sense not to do that. For example, in deno_graph we no longer have these files checked in https://github.com/denoland/deno_graph and we build the JS library to a folder, then publish to deno.land/x via a git branch with the help of (https://github.com/denoland/publish-folder)

**Comment by sigmaSd** [comment]
The problem is `deno task wasmbuild --check` if you run this right now on this repo it will pass but if you run `deno task wasmbuild build` and you run `git diff` you can see there are some changes

Is this whats supposed to happen ? if so can we either upgrade check to catch such changes (and make sure it run on the ci) or make `deno task wasmbuild build` a ci step and if git status is different then clean it errors
